name: Deploy to EC2
# Testing workflow trigger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Store SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem

      - name: Add EC2 host to known_hosts
        run: ssh-keyscan -H ec2-54-210-182-168.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/ec2_key.pem ubuntu@ec2-54-210-182-168.compute-1.amazonaws.com '
            cd /home/ubuntu/portfolio &&
            git pull origin main &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            cd portfolio &&
            python3 manage.py migrate &&
            python3 manage.py collectstatic --noinput &&
            sudo systemctl restart gunicorn &&
            sudo systemctl restart nginx
          '
